### ISSUE TITLE
could not add_pass_code_line

### ISSUE THREAD

**Issue by crypt0miester** [crypt0miester/cm-with-locker#1]
the instruction to add_pass_code_lines fails from the cli and from the progarm. both have to be rewritten somehow. even though it took a while for me to write them.

displayed below is the issue:
![Screenshot from 2022-05-03 17-22-43](https://user-images.githubusercontent.com/77497858/166506245-d55f589f-5d1c-456e-a924-44c2fbeff6db.png)

as you can see the passCodeLine args is empty, only the first code is attached out of the other. 

referred [here](https://github.com/crypt0miester/cm-with-locker/blob/dddae5a19038e1a5e049b85cc295cf3d101fcb69/metaplex/js/packages/cli/src/helpers/generate-passes.ts#L183) 

any help would be appreciated.

**Comment by staccDOTsol** [comment]
<img width="939" alt="image" src="https://user-images.githubusercontent.com/22843601/166508153-341cf013-68c6-4d95-8759-9c419175f811.png">

**Comment by crypt0miester** [comment]
hmmm thanks mate,

**Comment by staccDOTsol** [comment]
onto something

**Comment by crypt0miester** [comment]
> onto something

trying my best mate.
